networks:
  ergo_network:
    driver: bridge

services:

  ai-engine:
    build:
      context: ./backend/Ergo.AIEngine
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/Ergo.AIEngine/app:/code/app
    networks:
      - ergo_network
  
  work-session:
    build:
      context: ./backend/Ergo.WorkSession
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_PASSWORD=${DB_PASSWORD_SESSION}
      - AIEngine__BaseUrl=http://ai-engine:8000
    volumes:
      - ./docker-db/session:/app/data
    networks:
      - ergo_network
    depends_on:
      - ai-engine