// <auto-generated />
using System;
using Ergo.WorkSession.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ergo.WorkSession.Infrastructure.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20260415025929_InitialMonolith")]
    partial class InitialMonolith
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Ergo.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.PomodoroSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BreakDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("PomodoroSettings", (string)null);
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.PostureEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_event");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_alert");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("WorkSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_session");

                    b.HasKey("Id");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("PostureEvents", (string)null);
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.ReferencePose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id_reference_pose");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_persistent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vector_json");

                    b.HasKey("Id");

                    b.ToTable("ReferencePoses", (string)null);
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.WorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id_session");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<Guid?>("ReferencePoseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_reference_pose");

                    b.Property<double?>("ScoreAverage")
                        .HasColumnType("REAL")
                        .HasColumnName("score_average");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkSessions", (string)null);
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.PostureEvent", b =>
                {
                    b.HasOne("Ergo.WorkSession.Domain.Entities.WorkSession", null)
                        .WithMany("Events")
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.WorkSession", b =>
                {
                    b.HasOne("Ergo.Core.Entities.User", "User")
                        .WithMany("WorkSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ergo.Core.Entities.User", b =>
                {
                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("Ergo.WorkSession.Domain.Entities.WorkSession", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
